package edu.unc.cs.robotics.ros.msg.control;

import edu.unc.cs.robotics.ros.msg.Header;
import edu.unc.cs.robotics.ros.msg.MessageDeserializer;
import edu.unc.cs.robotics.ros.msg.MessageSerializer;
import edu.unc.cs.robotics.ros.msg.MessageSpec;
import edu.unc.cs.robotics.ros.msg.actionlib.ActionResult;
import edu.unc.cs.robotics.ros.msg.actionlib.GoalStatus;

@MessageSpec(
    type = FollowJointTrajectoryActionResult.DATATYPE,
    md5sum = FollowJointTrajectoryActionResult.MD5SUM,
    definition = FollowJointTrajectoryActionResult.DESCRIPTION
)
public class FollowJointTrajectoryActionResult extends ActionResult<FollowJointTrajectoryResult> {
    public static final String DATATYPE = "control_msgs/FollowJointTrajectoryActionResult";
    public static final String MD5SUM = "c4fb3b000dc9da4fd99699380efcc5d9";
    public static final String DESCRIPTION = "" +
                                             "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n" +
                                             "\n" +
                                             "Header header\n" +
                                             "actionlib_msgs/GoalStatus status\n" +
                                             "FollowJointTrajectoryResult result\n" +
                                             "\n" +
                                             "================================================================================\n" +
                                             "MSG: std_msgs/Header\n" +
                                             "# Standard metadata for higher-level stamped data types.\n" +
                                             "# This is generally used to communicate timestamped data \n" +
                                             "# in a particular coordinate frame.\n" +
                                             "# \n" +
                                             "# sequence ID: consecutively increasing ID \n" +
                                             "uint32 seq\n" +
                                             "#Two-integer timestamp that is expressed as:\n" +
                                             "# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n" +
                                             "# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n" +
                                             "# time-handling sugar is provided by the client library\n" +
                                             "time stamp\n" +
                                             "#Frame this data is associated with\n" +
                                             "# 0: no frame\n" +
                                             "# 1: global frame\n" +
                                             "string frame_id\n" +
                                             "\n" +
                                             "================================================================================\n" +
                                             "MSG: actionlib_msgs/GoalStatus\n" +
                                             "GoalID goal_id\n" +
                                             "uint8 status\n" +
                                             "uint8 PENDING         = 0   # The goal has yet to be processed by the actionlib server\n" +
                                             "uint8 ACTIVE          = 1   # The goal is currently being processed by the actionlib server\n" +
                                             "uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n" +
                                             "                            #   and has since completed its execution (Terminal State)\n" +
                                             "uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the actionlib server (Terminal State)\n" +
                                             "uint8 ABORTED         = 4   # The goal was aborted during execution by the actionlib server due\n" +
                                             "                            #    to some failure (Terminal State)\n" +
                                             "uint8 REJECTED        = 5   # The goal was rejected by the actionlib server without being processed,\n" +
                                             "                            #    because the goal was unattainable or invalid (Terminal State)\n" +
                                             "uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n" +
                                             "                            #    and has not yet completed execution\n" +
                                             "uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n" +
                                             "                            #    but the actionlib server has not yet confirmed that the goal is canceled\n" +
                                             "uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n" +
                                             "                            #    and was successfully cancelled (Terminal State)\n" +
                                             "uint8 LOST            = 9   # An actionlib client can determine that a goal is LOST. This should not be\n" +
                                             "                            #    sent over the wire by an actionlib server\n" +
                                             "\n" +
                                             "#Allow for the user to associate a string with GoalStatus for debugging\n" +
                                             "string text\n" +
                                             "\n" +
                                             "\n" +
                                             "================================================================================\n" +
                                             "MSG: actionlib_msgs/GoalID\n" +
                                             "# The stamp should store the time at which this goal was requested.\n" +
                                             "# It is used by an actionlib server when it tries to preempt all\n" +
                                             "# goals that were requested before a certain time\n" +
                                             "time stamp\n" +
                                             "\n" +
                                             "# The id provides a way to associate feedback and\n" +
                                             "# result message with specific goal requests. The id\n" +
                                             "# specified must be unique.\n" +
                                             "string id\n" +
                                             "\n" +
                                             "\n" +
                                             "================================================================================\n" +
                                             "MSG: control_msgs/FollowJointTrajectoryResult\n" +
                                             "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n" +
                                             "int32 error_code\n" +
                                             "int32 SUCCESSFUL = 0\n" +
                                             "int32 INVALID_GOAL = -1\n" +
                                             "int32 INVALID_JOINTS = -2\n" +
                                             "int32 OLD_HEADER_TIMESTAMP = -3\n" +
                                             "int32 PATH_TOLERANCE_VIOLATED = -4\n" +
                                             "int32 GOAL_TOLERANCE_VIOLATED = -5\n" +
                                             "\n" +
                                             "# Human readable description of the error code. Contains complementary\n" +
                                             "# information that is especially useful when execution fails, for instance:\n" +
                                             "# - INVALID_GOAL: The reason for the invalid goal (e.g., the requested\n" +
                                             "#   trajectory is in the past).\n" +
                                             "# - INVALID_JOINTS: The mismatch between the expected controller joints\n" +
                                             "#   and those provided in the goal.\n" +
                                             "# - PATH_TOLERANCE_VIOLATED and GOAL_TOLERANCE_VIOLATED: Which joint\n" +
                                             "#   violated which tolerance, and by how much.\n" +
                                             "string error_string\n" +
                                             "\n";

    public FollowJointTrajectoryActionResult() {

    }

    public FollowJointTrajectoryActionResult(MessageDeserializer buf) {
        header = new Header(buf);
        status = new GoalStatus(buf);
        result = new FollowJointTrajectoryResult(buf);
    }

    @Override
    public void serialize(MessageSerializer buf) {
        header.serialize(buf);
        status.serialize(buf);
        result.serialize(buf);
    }
}
